language: cpp
compiler:
  - gcc
  - clang
env:
  global:
  - secure: "Slm+HqRT+Vy0SG7E9gEShuHvNz6XWRUmBhVBLVJEaYy/0Lo2qp4OjFEWDjiJwFIiXstW2Wclds4SuewAn3Tc4x7dsY+5uaMCX7S/HPzsBCjLXUwjKasUqEGaVTIYmtFJm57hOkz6K2SLUUV4intkMiwtCiq/R0xe92QTTKkHyfo="
  - APT_DEPENDENCIES="doxygen doxygen-latex libboost-all-dev libeigen3-dev libtinyxml-dev"
  - GIT_DEPENDENCIES="ros/console_bridge ros/urdfdom_headers ros/urdfdom"
  - DEBSIGN_KEYID=5AE5CD75
  - LCOV_IGNORE_RULES="*tests*"
notifications:
  email:
  - francois.keith@gmail.com
branches:
  only:
  - master
script: ./.travis/run build
after_success: ./.travis/run after_success
after_failure: ./.travis/run after_failure
before_install: ./.travis/run before_install
matrix:
  allow_failures:
    - compiler: clang
os:
  - linux
  - osx

